In [1]:
import sys
import numpy as np
import matplotlib.pyplot as plt
import random

np.random.seed(0)

In [2]:
# object layers

In [3]:
# model 3 neurons with 4 inputs (this is a layer)

X = [[1.0, 2.0, 3.0, 2.5], # training dataset (input data to NN), 3 samples
    [2.0, 5.0, -1.0, 2.],
    [-1.5, 2.7, 3.3, -0.8]]

# now hidden layers:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons): # pass in size of inputs (size of a single sample) and number of neurons
        # note 28:17 we won't need to take the transpose when we do the forward pass
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # shape is n_inputs x n_neurons
        self.biases = np.zeros((1, n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
    


In [4]:
n_inputs = 4 # number of features
n_neurons = 5 # whatever you want

layer1 = Layer_Dense(n_inputs, n_neurons)
layer2 = Layer_Dense(n_neurons, 2)

layer1.forward(X)
print(layer1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


In [5]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
