In [3]:
import sys
import numpy as np
import matplotlib.pyplot as plt
import random
import nnfs
from nnfs.datasets import spiral_data
import math

nnfs.init()

In [10]:
# softmax activation function. used for output layer on classifier nn model

# what do we do with our output values?

# first step in training a model: how wrong is this model? issues: bounding, every neuron is exclusive...
# no formal, uniform way to determine how wrong we are. softmax helps solve these issues. also, the
# problem of negativity...

# y = e^x --> solves the problem. none of our values are negative, and we don't lose the "meaning" in negative
# numbers; e.g., we don't have to equivocate a 9 and a -9

In [11]:
layer_outputs = [4.8, 1.21, 2.385] # let's assume index 0 is the predicted target

E = math.e

exp_values = np.exp(layer_outputs)

# we got rid of negatives w/o losing the meaning of a negative value.
#now we normalize the values. gives us a probablity distribution

norm_values = exp_values / np.sum(exp_values)

print(norm_values)
print(sum(norm_values))

[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [12]:
# to sum up: input -> exponentiate -> normalize -> output
# softmax = exponentiate + normalize

# next: convert this to work as a batch so we have a batch of inputs, get a batch of outputs:

In [13]:
layer_outs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]
    
                ]
exp_vals = np.exp(layer_outs)

# have to change how we get the sum. we want the sum of each input (so three sums)
norm_vals = exp_vals / np.sum(exp_vals, axis=1, keepdims=True) # axis = 1 to get the rows
print(norm_vals)

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [ ]:
# issue with exponents: it blows up.
# overflow prevention: subtract the largest value in that layer from all values in the layer. 
# this squishes all the values between 0 and 1